service: singular-lambda-demo
frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    useChildProcesses: true
    printOutput: false
  appsync-simulator:
    apiKey: da2-fakeApiId123456

  appSync:
      name: helloworld-graphql
      authenticationType: API_KEY
      dataSources:
        - type: AWS_LAMBDA
          name: LambdaGraphQLHandler
          config:
            functionName: graphqlHandler
      schema:
        - AppSync/schema.graphql
      mappingTemplatesLocation: AppSync/mapping-templates
      defaultMappingTemplates:
        request: request.vtl
        response: response.vtl
      mappingTemplates:
        - dataSource: LambdaGraphQLHandler
          type: Query
          field: userById
        - dataSource: LambdaGraphQLHandler
          type: Mutation
          field: createUser

provider:
  name: aws
  runtime: nodejs14.x
  region:  eu-west-1
  profile: non-prod
  lambdaHashingVersion: 20201221

functions:
  httpApiHandler:
    handler: src/baseHander.handler
    events:
      - httpApi:
          path: /
          method: "*"
      - httpApi:
          path: /{proxy+}
          method: "*"

  graphqlHandler:
    handler: src/baseHander.handler
